### ISSUE TITLE
Need actual rate date

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/BBcurrencyQuoteBot#3]
In this message:
![image](https://user-images.githubusercontent.com/38240269/143509775-691dd5e2-a77a-40d8-9df5-29760467fe18.png)

Need info about last update time. Because we can have old rates
for example:

rates updated: 5 minutes ago

info:
https://help.bots.business/libs/currencyquote#check-last-updated-time

**Comment by Untoldhacker-Dev** [comment]
#8 fixed
