### ISSUE TITLE
DRY - do not repeat yourself

### ISSUE THREAD

**Issue by bots-business** [Untoldhacker-Dev/BBcurrencyQuoteBot#7]
Please move same code to function:

https://github.com/Untoldhacker-Dev/BBcurrencyQuoteBot/blob/666d4a72b9374830716b13c9d678732adfea911c/commands/_inlineQuery.js#L96-L106

https://github.com/Untoldhacker-Dev/BBcurrencyQuoteBot/blob/666d4a72b9374830716b13c9d678732adfea911c/commands/_inlineQuery.js#L155-L159

and etc

**Comment by bots-business** [comment]
![image](https://user-images.githubusercontent.com/38240269/143510292-a8547db7-e44a-41de-a71c-eef59bc52983.png)


it is also same. Need finction here

**Comment by Untoldhacker-Dev** [comment]
#8 fixed
